### ISSUE TITLE
extension boards ?

### ISSUE THREAD

**Issue by dkuku** [cavocado/pinout#1]
Hi - I was waiting for a project like that. I have an extension board that has some description but it's not mapped to the raspberry pi pins at all - I need always to search for it online - do you consider to add such stuff to the library ?
Image and pinout mapping:
https://leeselectronic.com/en/product/150711-raspberry-pi-gpio-extension-board-v22.html
maybe something like:
```
Pinout.print()
|> Pinout.extension_board(:extension_board_v21)
```

**Comment by cavocado** [comment]
Yes, I think this could be added. The extension board can't be auto detected, but it could be added as another board with ASCII art. 

Would something like this work?

```
iex> Pinout.print("Raspberry Pi T-Cobbler")
(Insert T-Cobbler picture and pinout here)
```

Could you supply what the ASCII art and pinout would look like?
